package core.dc;

import javafx.util.Pair;

/**
 * Copyright : all rights reserved,rapidhere@gmail.com
 * Mail: rapidhere@gmail.com
 * Class :
 * Version :
 * Usage :
 */
public interface CatchAlgorithm {
    abstract public class Token implements Comparable {
        private Object token;

        public abstract byte[] dump();
        public abstract int hashCode();
        public boolean equals(Object o) {
            return this.hashCode() == o.hashCode();
        }

        public Object getToken() {
            return token;
        }

        public void setToken(Object o) {
            token = o;
        }
    }

    /**
     * Dump list of tokens into bytes and then we can retrieve these tokens from load function
     * NOTE: this function isn't used to dump tokens into original format
     *       compress and decompress function can use this function to dump bytes sequence if
     *       there dc info have token sequence
     * @param tokens tokens to dump
     * @return dumped bytes
     */
    byte[] dump(Token[] tokens);

    /**
     * Load token list from bytes array generated by dump function
     * NOTE: this function isn't used to load tokens from original format
     *      compress and decompress function can use this function to load tokens if
     *      there dc info have token sequence
     * @param bytes byte array
     * @param offset start offset
     * @param length length of byte
     * @return tokens list and remain offset
     */
    Pair<Token[], Integer> load(byte[] bytes, int offset, int length);

    /**
     * parse token list from bytes array
     * @param bytes byte array
     * @param offset start offset
     * @param length length of byte
     * @return tokens list and remain offset
     */
    Pair<Token[], Integer> parse(byte[] bytes, int offset, int length);
}
